name: 'Keploy-test-action'
on: 
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronise, updated, edited]
  push:
    branches:
      - main
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test-Report
        uses: keploy/testgpt@main
        with:
          command: 'node src/app.js' ## Command to run the application
