name: Keploy tests
on:
  push:
    branches:
      - main
  pull_request:
      branches:
      - main
      types: [opened, synchronise, reopened]
jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Commit
      uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: 18
    
    - name: Keploy Tests
      id: keploy-run-test
      run: |
        curl --silent --location "https://github.com/keploy/keploy/releases/latest/download/keploy_linux_amd64.tar.gz" | tar xz -C /tmp
        sudo mkdir -p /usr/local/bin && sudo mv /tmp/keploy /usr/local/bin/keploy
        
        # Install application dependencies
        npm install
        
        # Run the keploy captured tests
        sudo -E keploy test -c "node src/app.js"
