name: Keploy tests
on:
  push:
    branches:
      - main
jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test-Report
      uses: alphasians/test-reportql@main
      with:
        working-directory: /
        delay: 10
        command: node src/app.js
